### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [FactionsPro/Factions#1]
I get an error with this plugin when i use it with PureChat

[Server thread/CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'PureChat v1.4.0': Call to undefined method FactionsPro\FactionMain::getSession() on _64FF00\PureChat\PCListener
[14:03:29] [Server thread/CRITICAL]: Error: "Call to undefined method FactionsPro\FactionMain::getSession()" (EXCEPTION) in "/PureChat-master/src/_64FF00/PureChat/factions/FactionsProNew" at line 34

**Comment by ItzBulkDev** [comment]
This FactionsPro version's session ever to is not in the main file. You will need to edit PureChat until we add it to the main file

**Comment by XShockinFireX** [comment]
ok i fixed it anyway thanks
